# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1
###
# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Супер пупер Хрен5",
  "description": "Самый горький хрен на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/4/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=супер
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Завоз12",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/1/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 111,
      "price": 13.55
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 3.65
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
###
# поиск складов, где есть определенный продукт по имени
GET {{baseUrl}}/stocks/?search=Хрен
Content-Type: application/json
